### ISSUE TITLE
Updates not sent to REDCap

### ISSUE THREAD

**Issue by mperry94** [DecisionNeurosciencePsychopathology/redcap_in_r#2] opened 2018-06-13 17:37 UTC
Ran bsrc.ema.loopit(); updated % completion for K VES not sent to REDCap

**Comment by Jiazhouchen** [comment] 2018-06-13 20:41
Issue identified as the following:

-If the first subject has not yet completed, function will not successfully initialize during subject loop.

Issue is fixed in the latest update; might have unintended behavior; on close watch.

**Closed by Jiazhouchen** 2018-06-13 20:41 UTC
